"""Reference simulator for the Poll Backoff Contract.

THE canonical source of expected poll counts (Poll Backoff Contract, v27,
2026-07-23): the expected-count table is generated by ``python poll_sim.py``,
and each SDK's unit tests assert their client's observed poll count EQUALS this
simulator's output for the same parameters — an independent implementation of
the contract, so the comparison is a real cross-check, not a tautology.

Counting model (normative):
- polls == GETs; the first GET is issued immediately (t=0, job creation
  excluded from the budget);
- each GET costs ``rtt_s`` (the full round trip). The server SNAPSHOTS the
  job's status when it PROCESSES the request — modeled at the GET's ISSUE
  time ``t`` — and the response then travels back, landing at ``t + rtt``
  (v20). A real backend fixes ``job.status`` before serializing and
  transmitting, so it CANNOT reflect a completion that happens while the
  response is in flight; the pre-v20 model snapshotted at landing (t + rtt),
  which optimistically credited the response leg to the job and flipped
  boundary cases (e.g. job_29.97s at rtt 80 ms) to success where a real
  server times them out. A job of duration D is therefore terminal on the
  first GET ISSUED at or after D (its response landing at D_issue + rtt);
- ``draw`` is the U(0,1) jitter draw: 0.5 = expected value, 0.0 = worst case
  (max polls);
- the wall-clock budget is checked before each GET; sleeps are bounded by the
  remaining budget;
- strict acceptance (v5+): the deadline is checked when the response LANDS
  (at t + rtt) and BEFORE the terminal check — a response landing at/after
  the deadline times out, even a terminal one, matching the SDK loops. So a
  GET whose snapshot saw the job terminal still times out if its response
  lands past the deadline (snapshot→acceptance ≤ rtt).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Optional, Sequence, Union

WARM_S = 1.5
RAMP_S = (0.1, 0.2, 0.4, 0.8, 1.0)
HARD_CAP_S = 5.0
HINT_MIN_MS = 50
HINT_MAX_MS = 5000
# Final-poll reserve (v10): a pending-path sleep that would otherwise reach
# the deadline is shortened so ONE last GET is ISSUED with the reserve
# remaining. The reserve guarantees the ISSUE, not the completion: the
# response is accepted only when it lands STRICTLY inside the budget, so the
# final GET succeeds iff its full round trip (network + body read + the
# loop's acceptance check) takes strictly LESS than the reserve — at exactly
# 100 ms the strict boundary rejects it (v12; pinned by the
# job_29.89s_plain_rtt_* canonical pair). Without the reserve, a hint
# comparable to the remaining budget turns a would-succeed job into a
# poll-timeout (e.g. a 29 s job with a 5 s hint and a 30 s budget). v14
# made the reserve STATEFUL (first natural inside-reserve landing polls
# immediately); v15 replaces the post-tail-poll "sleep to the deadline"
# with CALLER-PACED tail polling (min(interval, remaining)) — sleeping to
# the deadline forfeited round trips that still fit the budget whenever
# interval + rtt < remaining (a 2.914 s job under a 3 s budget timed out
# with 86 ms still on the clock). Together with both densification bounds
# this yields the UNIVERSAL WINDOW guarantee, for round trips strictly
# inside the reserve: any job completing at least
#     W = rtt + min(RESERVE, interval + rtt)
# before the deadline succeeds under ANY schedule, hinted or plain —
# property-swept over timeouts x intervals x rtts x hints x draws. Inside
# W the outcome is a landing-phase lottery; it is NOT symmetric near
# rtt == reserve (the hinted schedule's last useful GET is issued earlier
# on average), which the terminal-window scan pins with exact counts.
FINAL_POLL_RESERVE_S = 0.1

# A dynamic hint schedule for the wire: [t_from_s, hint_ms] steps — the hint
# at response time t is the value of the LAST step with t_from STRICTLY < t
# (the first step's value when none is). Transitions are EXCLUSIVE at the
# boundary (v13): the backend ladder keeps the old rung at exact equality
# (`raw_ms <= step`, poll_hint_service.to_ladder_ms), so at t exactly 16.0 s
# the age floor is still 2000 — an inclusive `t >= t_from` lookup diverged
# from the deployed formula at every rung boundary. This is the
# JSON-serializable form of a callable schedule, shared by the canonical
# cases and the SDK test harnesses (a callable can't live in poll_cases.json).
HintSchedule = Sequence[Sequence[float]]
HintSpec = Union[int, Callable[[float], Optional[int]], None]


def schedule_fn(schedule: HintSchedule) -> Callable[[float], Optional[int]]:
    def hint(t: float) -> Optional[int]:
        value = int(schedule[0][1])
        for t_from, ms in schedule:
            if t > t_from:
                value = int(ms)
        return value

    return hint


# A VARIABLE round-trip schedule (v18): [poll_from, rtt_ms] steps — the rtt
# for poll index i (1-based) is the value of the LAST step with poll_from
# STRICTLY < i (the first step's value when none is). The JSON-serializable
# form of a callable rtt (a callable can't live in poll_cases.json), used to
# replay a per-poll-varying round trip through the real SDK loops — a
# constant rtt models ZERO variance and can't exercise the max-vs-average
# distinction the window guarantee rests on.
def rtt_schedule_fn(schedule: HintSchedule) -> Callable[[int], float]:
    def rtt(i: int) -> float:
        value = float(schedule[0][1])
        for poll_from, ms in schedule:
            if i > poll_from:
                value = float(ms)
        return value / 1000.0

    return rtt


@dataclass
class SimResult:
    polls: int
    latency_s: float
    timed_out: bool


def simulate(
    job_s: float,
    *,
    interval_s: float = 0.05,
    rtt_s: Union[float, Callable[[int], float]] = 0.01,
    timeout_s: float = 30.0,
    draw: Union[float, Callable[[int], float]] = 0.5,
    hint_ms: HintSpec = None,
) -> SimResult:
    cap_eff = max(HARD_CAP_S, interval_s)
    t = 0.0
    polls = 0
    ramp_i = 0
    # Stateful final-poll reserve (v14): True once the reserve-preserved
    # final GET has been scheduled — either via a tail-shortened sleep or
    # via the immediate inside-reserve poll below.
    tail_poll_spent = False
    while True:
        if timeout_s - t <= 0:
            return SimResult(polls, t, True)
        polls += 1
        # The server snapshots job.status when it PROCESSES this GET —
        # modeled at ISSUE time (v20). It cannot report a completion that
        # happens while the response is travelling back.
        snapshot_t = t
        # rtt_s may be a callable(poll_index) -> float (v18): a VARIABLE
        # round trip. The universal-window guarantee needs an UPPER bound on
        # EVERY poll's rtt, not an average — a single latency spike on the
        # final guard poll can land it past the deadline. A constant rtt_s
        # models zero variance, so a callable is the only way to exercise
        # the spike (poll_index is 1-based: this poll's number).
        this_rtt = rtt_s(polls) if callable(rtt_s) else rtt_s
        t += this_rtt  # response lands
        if t >= timeout_s:
            # Strict acceptance boundary: landed at/after the deadline —
            # rejected even if the snapshot was terminal.
            return SimResult(polls, t, True)
        if snapshot_t >= job_s:
            # The server SAW the job terminal at snapshot time and the
            # response landed strictly inside the budget.
            return SimResult(polls, t, False)
        warm = t < WARM_S
        if warm:
            sleep = interval_s
        else:
            base = max(RAMP_S[ramp_i], interval_s)
            ramp_i = min(ramp_i + 1, len(RAMP_S) - 1)
            # hint_ms may be a callable(t) -> Optional[int]: a DYNAMIC hint
            # schedule (e.g. the backend's per-phase age floor). The server
            # computes BOTH the status and the hint in ONE response, at the
            # request-processing SNAPSHOT time — NOT at landing (v20 fixed
            # status at snapshot but left the hint at landing t, a two-slice
            # response no real route emits; v21 evaluates the hint at
            # ``snapshot_t`` too).
            hint_val = hint_ms(snapshot_t) if callable(hint_ms) else hint_ms
            if hint_val is not None and type(hint_val) is int and HINT_MIN_MS <= hint_val <= HINT_MAX_MS:
                target = min(max(base, hint_val / 1000.0), cap_eff)
            else:
                target = min(base, cap_eff)
            # Deadline-aware densification (v14): the target never exceeds
            # HALF the remaining budget (floored at the caller's interval),
            # so as the deadline nears the schedule geometrically approaches
            # the plain schedule's landing density — a sparse hinted tail
            # otherwise gambles away a job completing just inside the
            # budget on a single landing.
            target = min(target, max((timeout_s - t) / 2.0, interval_s))
            # Ramp-in bound (v15, symmetric to densification): the target
            # never exceeds HALF the job's own elapsed time either — a host
            # hint (max(host_rung, age_rung) with a slow host median) used
            # to jump a job straight from the warm phase into 5 s sleeps,
            # costing a 1.6 s job +4.4 s. The geometric ramp-in caps the
            # overhead at ~60 % of the job's own duration while converging
            # to the full hint within a few sleeps on genuinely long jobs.
            target = min(target, max(t / 2.0, interval_s))
            lo = max(0.8 * target, interval_s)
            hi = min(1.2 * target, cap_eff)
            # draw may be a callable(poll_index) -> float: an adversarial
            # JITTER SEQUENCE (v14) — a constant draw cannot hit corner
            # cases that need different jitter on different sleeps.
            d = draw(polls) if callable(draw) else draw
            sleep = lo if hi <= lo else lo + (hi - lo) * d
        # Bound with the final-poll reserve — mirrors PollPacer._bound.
        # v14 made the reserve STATEFUL: a pending response can LAND inside
        # the reserve window naturally (long hinted sleep + real RTT), and
        # v10-v13's "sleep runs to the deadline" branch then never issued
        # the final GET at all. The FIRST inside-reserve pending landing
        # polls again IMMEDIATELY (still time for a < remaining round
        # trip). v15: AFTER that tail poll, polling continues at the
        # CALLER'S OWN interval until the deadline instead of sleeping the
        # whole remainder — the caller-sanctioned density is not a burst,
        # and sleeping to the deadline forfeited round trips that still fit
        # whenever interval + rtt < remaining (the custom-timeout
        # counterexample: 2.914 s job, 3 s budget, timed out 86 ms early).
        remaining = timeout_s - t
        tail = max(0.0, remaining - FINAL_POLL_RESERVE_S)
        if sleep <= tail:
            t += sleep
        elif remaining > FINAL_POLL_RESERVE_S:
            tail_poll_spent = True
            t += tail
        elif not tail_poll_spent:
            tail_poll_spent = True  # immediate final GET: sleep 0
        else:
            t += min(interval_s, max(0.0, remaining))  # caller-paced tail (v15)


# The deployed backend age floor (poll_hint_service: ladder(phase_age / 8))
# as a step schedule — the LOW-host-median dynamic-hint scenario. Steps are
# the points where ladder((t * 1000) / 8) changes rung.
AGE_FLOOR_SCHEDULE = (
    (0.0, 50), (0.4, 100), (0.8, 200), (1.6, 500),
    (4.0, 1000), (8.0, 2000), (16.0, 5000),
)

# The canonical cross-SDK case list. `python poll_sim.py --json` regenerates
# sdk/conformance/poll_cases.json — the single source the Node and .NET
# suites load (hand-copied numbers drift); a Python test guards the checked-in
# file against the live simulator. Per-case `rtt_s` overrides the top-level
# default; `hint_schedule` is the serialized dynamic-hint form (schedule_fn).
CANONICAL_CASES = (
    {"name": "job_0.3s_draw_0.5", "job_s": 0.3, "draw": 0.5, "hint_ms": None},
    {"name": "job_8s_draw_0.5", "job_s": 8.0, "draw": 0.5, "hint_ms": None},
    {"name": "job_11s_draw_0.5", "job_s": 11.0, "draw": 0.5, "hint_ms": None},
    {"name": "job_8s_draw_0.0", "job_s": 8.0, "draw": 0.0, "hint_ms": None},
    {"name": "job_999s_draw_0.5", "job_s": 999.0, "draw": 0.5, "hint_ms": None},
    {"name": "job_8s_draw_0.5_hint_5000", "job_s": 8.0, "draw": 0.5, "hint_ms": 5000},
    # The final-poll-reserve guard case (v10): a job finishing just inside the
    # budget with a hint comparable to the remaining budget MUST succeed.
    {"name": "job_29s_draw_0.5_hint_5000", "job_s": 29.0, "draw": 0.5, "hint_ms": 5000},
    # v12's boundary scenario, RESCUED by v14 densification: both round
    # trips now land a pending poll early enough that the densified tail
    # catches the 29.3 s completion inside the budget — kept as regression
    # guards for the densified trajectory.
    {"name": "job_29.3s_hint_5000_rtt_0.099", "job_s": 29.3, "draw": 0.5,
     "hint_ms": 5000, "rtt_s": 0.099},
    {"name": "job_29.3s_hint_5000_rtt_0.1", "job_s": 29.3, "draw": 0.5,
     "hint_ms": 5000, "rtt_s": 0.1},
    # Inside the universal window the outcome is a LOTTERY the contract
    # does not promise to win (v15): a job completing 10 ms before the
    # deadline at a round trip near the reserve times out hinted — pinned
    # as the honest-window case (pre-v15 this pair pinned the strict
    # boundary; the deciding GET is no longer deterministic there, so the
    # boundary pin moved to the job_29.89s_plain pair below).
    {"name": "job_29.99s_hint_5000_rtt_0.099", "job_s": 29.99, "draw": 0.5,
     "hint_ms": 5000, "rtt_s": 0.099},
    {"name": "job_29.99s_hint_5000_rtt_0.1", "job_s": 29.99, "draw": 0.5,
     "hint_ms": 5000, "rtt_s": 0.1},
    # The reserve's STRICT boundary (v12, re-pinned for v15 on the plain
    # schedule): a job whose ONLY catching GET is the reserve GET issued at
    # exactly 29.9 s — the two runs are poll-for-poll identical and differ
    # only in the final landing: 29.9 + 0.099 = 29.999 (strictly inside,
    # accepted) vs 29.9 + 0.1 = 30.0 (AT the deadline, rejected).
    {"name": "job_29.89s_plain_rtt_0.099", "job_s": 29.89, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.099},
    {"name": "job_29.89s_plain_rtt_0.1", "job_s": 29.89, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.1},
    # The DYNAMIC hint (v12): each poll carries the backend age floor for its
    # own response time — real SDK loops must handle a hint that changes
    # between polls, not just a constant.
    {"name": "job_11s_draw_0.5_age_schedule", "job_s": 11.0, "draw": 0.5,
     "hint_ms": None, "hint_schedule": [list(step) for step in AGE_FLOOR_SCHEDULE]},
    # v13's KNOWN violation, RESCUED by v14: at a round trip equal to the
    # reserve the hinted sparse tail used to leave only a doomed final GET
    # (26 polls, timeout) while plain succeeded. Densification + the
    # stateful tail poll now land the hinted schedule inside the budget
    # too — kept as the v13→v14 regression pair.
    {"name": "job_29.3s_rtt_0.1_plain", "job_s": 29.3, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.1},
    {"name": "job_29.3s_age_schedule_rtt_0.1", "job_s": 29.3, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.1,
     "hint_schedule": [list(step) for step in AGE_FLOOR_SCHEDULE]},
    # The v14 "production counterexample" pair — RECLASSIFIED by the v20
    # honest server-snapshot model. A 29.97 s job at an 80 ms round trip
    # completes only 30 ms before the deadline: INSIDE the window
    # W = 0.08 + min(0.1, 0.13) = 0.18 s. v14 claimed both the plain and the
    # production-hinted (host jumps to 5000 at t=6) schedules were "rescued"
    # to success here, but that was an ARTIFACT of the pre-v20 model that
    # snapshotted the job state at RESPONSE-LANDING (crediting the 80 ms
    # response leg to the job). Under the honest model the server snapshots
    # at GET-processing time, so BOTH time out — which the guarantee permits
    # (inside W is a lottery). Poll counts unchanged (43 / 28); kept as the
    # honest inside-W pair.
    {"name": "job_29.97s_rtt_0.08_plain", "job_s": 29.97, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.08},
    {"name": "job_29.97s_host5000_at_6_rtt_0.08", "job_s": 29.97, "draw": 0.5,
     "hint_ms": None, "rtt_s": 0.08,
     "hint_schedule": [[0.0, 50], [0.4, 100], [0.8, 200], [1.6, 500],
                       [4.0, 1000], [6.0, 5000]]},
    # The post-warm CLIFF, fixed by the v15 ramp-in bound: a slow host
    # median (host rung 5000) used to jump a 1.6 s job from the warm phase
    # straight into a 4.5 s sleep — completion at 6.02 s instead of 1.62 s.
    # The geometric ramp-in observes it at 2.275 s with the same poll count
    # as plain.
    {"name": "job_1.6s_host5000", "job_s": 1.6, "draw": 0.5, "hint_ms": 5000},
    # The CUSTOM-TIMEOUT counterexample, fixed by the v15 caller-paced
    # tail: under a 3 s budget the age-hinted schedule spent its tail poll
    # 4 ms before completion and then slept the whole remainder — timing
    # out with 86 ms (> interval + rtt) still on the clock, while plain
    # succeeded. Caller-paced tail polling catches it in-budget. Per-case
    # `timeout_s` — the contract holds for EVERY supported budget, not
    # just the 30 s default.
    {"name": "job_2.914s_age_schedule_timeout_3", "job_s": 2.914, "draw": 0.0,
     "hint_ms": None, "timeout_s": 3.0,
     "hint_schedule": [list(step) for step in AGE_FLOOR_SCHEDULE]},
    # A CUSTOM caller INTERVAL (200 ms, off the 50 ms default): the warm
    # phase, ramp floor and jitter range all key off caller_interval, so a
    # non-default interval exercises code the default cases never do (v16).
    # Replayed through BOTH loops of every SDK — the interval sweep was
    # simulator-only.
    {"name": "job_5s_interval_0.2_draw_0.5", "job_s": 5.0, "draw": 0.5,
     "hint_ms": None, "interval_s": 0.2},
    # A custom interval TOGETHER WITH a hint (v17): the ramp floor keys off
    # caller_interval AND max(base, hint) applies — the v16 custom-interval
    # case had hint_ms null, so the interval x hint interaction was
    # uncovered outside the simulator sweep.
    {"name": "job_8s_interval_0.2_hint_5000", "job_s": 8.0, "draw": 0.5,
     "hint_ms": 5000, "interval_s": 0.2},
    # An interval ABOVE the 5 s hard cap (v17): cap_eff = max(5 s,
    # caller_interval) must honor a 10 s interval verbatim rather than
    # clamping to 5 s — the only case that exercises the cap_eff branch
    # through the real loops.
    {"name": "job_25s_interval_10_draw_0.5", "job_s": 25.0, "draw": 0.5,
     "hint_ms": None, "interval_s": 10.0},
    # A VARIABLE round trip within the reserve bound (v18): the rtt starts
    # at 10 ms and steps up to 50 ms after the 20th poll — both under the
    # 100 ms reserve, so the job still succeeds. A constant rtt models zero
    # variance; this replays a per-poll-varying round trip through the real
    # SDK loops (rtt_schedule, the JSON form of the callable rtt).
    {"name": "job_8s_rtt_schedule", "job_s": 8.0, "draw": 0.5, "hint_ms": None,
     "rtt_schedule": [[0, 10], [20, 50]]},
    # A TAIL case combining a VARIABLE round trip AND a production age hint
    # (v20): a 29.5 s job (outside W ≈ 100 ms) with a per-poll-varying rtt
    # (10 → 50 → 20 ms, all under the reserve) and the dynamic age-floor
    # hint. It exercises the reserve/densification tail with BOTH a changing
    # rtt and a changing hint at once, replayed through both loops of every
    # SDK — the variable-RTT coverage was otherwise unhinted and far from
    # the deadline tail.
    {"name": "job_29.5s_rtt_schedule_age_hint", "job_s": 29.5, "draw": 0.5,
     "hint_ms": None, "rtt_schedule": [[0, 10], [15, 50], [30, 20]],
     "hint_schedule": [list(step) for step in AGE_FLOOR_SCHEDULE]},
)


def canonical_cases() -> dict:
    cases = []
    for spec in CANONICAL_CASES:
        hint: HintSpec = spec["hint_ms"]
        if spec.get("hint_schedule") is not None:
            hint = schedule_fn(spec["hint_schedule"])
        rtt: Union[float, Callable[[int], float]] = spec.get("rtt_s", 0.01)
        if spec.get("rtt_schedule") is not None:
            rtt = rtt_schedule_fn(spec["rtt_schedule"])
        result = simulate(
            spec["job_s"],
            draw=spec["draw"],
            hint_ms=hint,
            rtt_s=rtt,
            timeout_s=spec.get("timeout_s", 30.0),
            interval_s=spec.get("interval_s", 0.05),
        )
        cases.append({**spec, "polls": result.polls, "timed_out": result.timed_out})
    return {"interval_s": 0.05, "rtt_s": 0.01, "timeout_s": 30.0, "cases": cases}


def _flat(job_s: float, interval_s: float = 0.05, rtt_s: float = 0.01, timeout_s: float = 30.0) -> SimResult:
    """Pre-amendment behavior for the comparison column."""
    t = 0.0
    polls = 0
    while True:
        polls += 1
        t += rtt_s
        if t >= job_s:
            return SimResult(polls, t, False)
        if t >= timeout_s:
            return SimResult(polls, t, True)
        t += interval_s


if __name__ == "__main__":
    import sys

    if "--json" in sys.argv:
        import json

        print(json.dumps(canonical_cases(), indent=2))
        raise SystemExit(0)
    print("Poll Backoff Contract — canonical table (interval 50 ms, rtt 10 ms)")
    print(f"{'job':>8} | {'expected':>8} | {'worst':>6} | {'flat today':>10}")
    for job in (0.3, 8.0, 11.0, 30.0):
        exp = simulate(job, draw=0.5)
        worst = simulate(job, draw=0.0)
        flat = _flat(job)
        star = " (timeout)" if exp.timed_out else ""
        print(
            f"{job:>7.1f}s | {exp.polls:>8} | {worst.polls:>6} | {flat.polls:>10}{star}"
        )
